CREATE TABLE models.undefended_frontpage_attacks (
    modelid SERIAL PRIMARY KEY,
    auc NUMERIC NOT NULL,
    model_timestamp TIMESTAMP NOT NULL,
    numfolds NUMERIC,
    train_class_balance NUMERIC,
    world_type VARCHAR(30),
    model_type VARCHAR(100),
    observed_world_fraction NUMERIC,
    base_rate NUMERIC,
    hyperparameters JSON NOT NULL,
    tpr NUMERIC ARRAY,
    fpr NUMERIC ARRAY,
    precision_at_0_point_01_percent NUMERIC,
    precision_at_0_point_05_percent NUMERIC,
    precision_at_0_point_1_percent NUMERIC,
    precision_at_0_point_5_percent NUMERIC,
    precision_at_1_percent NUMERIC,
    precision_at_5_percent NUMERIC,
    precision_at_10_percent NUMERIC,
    recall_at_0_point_01_percent NUMERIC,
    recall_at_0_point_05_percent NUMERIC,
    recall_at_0_point_1_percent NUMERIC,
    recall_at_0_point_5_percent NUMERIC,
    recall_at_1_percent NUMERIC,
    recall_at_5_percent NUMERIC,
    recall_at_10_percent NUMERIC,
    f1_at_0_point_01_percent NUMERIC,
    f1_at_0_point_05_percent NUMERIC,
    f1_at_0_point_1_percent NUMERIC,
    f1_at_0_point_5_percent NUMERIC,
    f1_at_1_percent NUMERIC,
    f1_at_5_percent NUMERIC,
    f1_at_10_percent NUMERIC
);
